### ISSUE TITLE
How to use your lib?

### ISSUE THREAD

**Issue by COM8** [langboost/libsignal-protocol-pcl#6]
Is there any documentation available about how to use your library?

**Comment by jeff-r-skillrev** [comment]
One thing to keep in mind is that it's nearly identical to the Java
implementation. So studying Signal's code base may be useful. Also, I have
a little "hello world" style app as a repository that implements a tiny
example.

**Comment by COM8** [comment]
Thanks for the response found your example:
https://github.com/langboost/axolotl-sample-client
